
version: '2'
volumes:
    grafana_data: {}
    prometheus_data: {}
    influxdb_data: {}

services:
# -------------------------------------------------------------------------
# Grafana - Graphical Interface
# -------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:6.7.6
    volumes:
      - /etc/localtime:/etc/localtime
      - grafana_data:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

# -------------------------------------------------------------------------
# Prometheus
# -------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules:/etc/prometheus/alert.rules
      - /etc/localtime:/etc/localtime
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=365d'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    ports:
      - '9090:9090'

# -------------------------------------------------------------------------
# Influxdb + Chronograf
# -------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.8.9
    volumes:
      - /etc/localtime:/etc/localtime
      - ./influxdb/scripts/:/docker-entrypoint-initdb.d/
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_MONITOR_STORE_ENABLED=0
      #- INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      #- INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: unless-stopped
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:latest
    volumes:
      - /var/lib/chronograf:/var/lib/chronograf
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      #- INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      #- INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - '8888:8888'

# -------------------------------------------------------------------------
# Telegraf - Prometheus (Alerts and Perfmon)
# -------------------------------------------------------------------------
  telegraf-prom:
    image: apstra/telegraf:latest
    command: telegraf -debug
    restart: unless-stopped
    env_file:
      - variables.env
    volumes:
      - ./config/telegraf-prom.toml:/etc/telegraf/telegraf.conf
      - /etc/localtime:/etc/localtime
    ports:
      - '6666:6666'

# -------------------------------------------------------------------------
# Telegraf - Influx (Events)
# -------------------------------------------------------------------------
  telegraf-influx:
    image: apstra/telegraf:latest
    command: telegraf -debug
    restart: unless-stopped
    env_file:
      - variables.env
    volumes:
      - ./config/telegraf-influx.toml:/etc/telegraf/telegraf.conf
      - /etc/localtime:/etc/localtime
    ports:
      - '4444:4444'
