{
 "title": "Apstra AOS Device Interfaces",
 "tags": [
  "apstra",
  "aos",
  "device",
  "interface"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(interface_counters_tx_bps, device)"
    }
   },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(interface_counters_tx_bps{device=~\"$device\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TX Interface Traffic Statistics (bps)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(8*interface_counters_tx_bytes{device=~\"$device\"}/5) by (device, interface)",
     "legendFormat": "{{ interface }} - TX"
    }
   ]
  },
  {
   "title": "RX Interface Traffic Statistics (bps)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(8*interface_counters_rx_bytes{device=~\"$device\"}/5) by (device, interface)",
     "legendFormat": "{{ interface }} - RX"
    }
   ]
  },
  { "title": "Traffic Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Traffic Total (PPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "pps", "label": "RX / TX" }
   ],
   "targets": [
    {
     "expr": "sum(interface_counters_tx_unicast_pps{device=~\"$device\"} + interface_counters_tx_broadcast_pps{device=~\"$device\"} + interface_counters_tx_multicast_pps{device=~\"$device\"}) by (device, interface)",
     "legendFormat": "{{ interface }} - TX"
    },
    {
     "expr": "sum(interface_counters_rx_unicast_pps{device=~\"$device\"} + interface_counters_rx_broadcast_pps{device=~\"$device\"} + interface_counters_rx_multicast_pps{device=~\"$device\"}) by (device, interface)",
     "legendFormat": "{{ interface }} - RX"
    }
   ]
  },
  {
   "title": "Stack Traffic Statistics (bps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "RX / TX" }
   ],
   "targets": [
    {
     "expr": "avg(8*interface_counters_tx_bytes{device=~\"$device\"}/5) by (device, interface)",
     "legendFormat": "{{ interface }} - TX"
    },
    {
     "expr": "avg(8*interface_counters_rx_bytes{device=~\"$device\"}/5) by (device, interface)",
     "legendFormat": "{{ interface }} - RX"
    }
   ]
  },
  { "title": "Interface $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "interface" },
  {
   "title": "$device - $interface - Traffic Statistics (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avg(8*interface_counters_tx_bytes{device=~\"$device\",interface=\"$interface\"}/5) by (device, interface)",
     "legendFormat": "{{device}} - {{ interface }} - TX"
    },
    {
     "expr": "avg(8*interface_counters_rx_bytes{device=~\"$device\",interface=\"$interface\"}/5) by (device, interface)",
     "legendFormat": "{{device}} - {{ interface }} - RX"
    }
   ]
  }
 ]
}